# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python build.py
        
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        # GitHub repository where assets will be deployed (default current)
        repo: git@github.com:divanvisagie/divanvisagie.github.io.git
        # Git branch where assets will be deployed
        target_branch: master
        # Create incremental commit instead of doing push force
        keep_history: true
        # Allow an empty commit to be created
        allow_empty_commit: true # optional, default is true
        # Build directory to deploy
        build_dir: public
        # Commit author's name
        committer_name: Divan Visagie
        # Commit author's email
        committer_email: me@dvisagie.com # optional
        # Commit message
        commit_message: "Build from ci" # optional
        # Write the given domain name to the CNAME file
        fqdn: dvisagie.com # optional
